### ISSUE TITLE
Support calculation w/o graph?

### ISSUE THREAD

**Issue by jsa-aerial** [HarryStevens/d3-regression#14]
Quick question. Does this support the calculation of the various regressions and only returning the data results? Put another way, does this always render graphs or can that part be optional?

Thanks!

**Comment by HarryStevens** [comment]
Each generator returns an array of points to make it easier to display the regression line if you choose to do so. But you don't have to render the data to the DOM or display any visual representation of it at all. Each generator also returns properties that let you to reason about the data given the regression you've used: coefficients, an R-squared value, and a function that will return a y-value given an x-value.

**Comment by jsa-aerial** [comment]
Sounds great! That's what I was hoping. Thanks!
