### ISSUE TITLE
Confusing license

### ISSUE THREAD

**Issue by woody-li** [HarryStevens/d3-regression#32]
It returns GPL license via npm, but the LICENSE file is BSD.
Which is the right one?
`npm info d3-regression`
`d3-regression@1.3.4 | GPL-3.0 | deps: none | versions: 31`

https://github.com/HarryStevens/d3-regression/blob/master/LICENSE#L1

**Comment by HarryStevens** [comment]
Thanks @woody-li. This is fixed now.
